### ISSUE TITLE
Organization of the journal

### ISSUE THREAD

**Issue by leilaicruz** [T-Wisse/MEP_Thomas#1]
- The journal for a more effective organization should be divided in days or weeks. 
-  I propose you divided it in folders with the name of the month you are in with subfolders with the weeks within the month. Inside the subfolder of the weeks you can add your daily-log-files.md with the folllowing naming structure: YEAR-MONTH-DAY-logfile.md
- In those files you can also add images , links etc , so it really shows what you were doing including your methods and results . This will be useful for your report also at the end. 

So the structure will be:

Project-log/
├── README.md             # overview of the project
├── month-1/                 # data files used in the project
│   ├── README.md         # describes where data came from
│   └── Week-1/  
│   └────────2020-11-18-logfile.md/  
│   └── Week-2/  
│   └────────20XX-XX-XX-logfile.md/  

├── month-2/                 # data files used in the project
│   ├── README.md         # describes where data came from
│   └── Week-1/  
│   └────────2020-11-18-logfile.md/  
│   └── Week-2/  
│   └────────20XX-XX-XX-logfile.md/

**Comment by T-Wisse** [comment]
I have implemented version of this. The coding related folders are in this repo. Log related folders are in the journal_mep repo: https://github.com/T-Wisse/journal_mep
