### ISSUE TITLE
Using excel to save data is probably not best practice

### ISSUE THREAD

**Issue by T-Wisse** [T-Wisse/MEP_Thomas#13]
While excel is very useful and its files are mostly easily accessed with python, excel is not great to save data. This, because excel is 'smart' and interprets the input. As a result a gene name may converted to, for example, a date. While this is very rare and to my knowledge this does not actually occur for the genes in yeast, but it may still be a good idea to find another format.

**Comment by leilaicruz** [comment]
for me that also happens but not for many genes , actually these were very rare cases . My solution was to filter them out and delete those date names from the dataset.
Otherwise you could use tabular data in txt format , it is also another option

**Comment by T-Wisse** [comment]
I did a manual check which showed that no genes in the data I am using has this issue. As this is very rare I think we can keep using excel for convenience
