### ISSUE TITLE
Transform dbem1dbem3 and dbem3 strain (yTW001, yLIC137) with SATAY plasmid

### ISSUE THREAD

**Issue by leilaicruz** [T-Wisse/MEP_Thomas#15]

**Comment by T-Wisse** [comment]
Hypothesis (We believe that...)
We believe that we can make a strain with dbem1dbem3 and a plasmid for SATAY by transformation of yTW001 (dbem1dbem3) with this plasmid. We can do the same for a dbem3 strain (yLIC137).

Test (To verify that we will...)
To verify that we will perform the transformation.

False Test (To falsify that we should test...)
NA

Metric (And measure...)
NA

Criteria (We are right if...)
We are right if we observe yeast colonies grow on the selection plates. These plates are -ura + ade. These strains should be able to grow on these plates only if they contain the plasmid

Observation (We observed...)
We observed colonies on the selection plates which smell like yeast.

Learnings and insights (From that we learned that...)
We have transformed our strains with the desired plasmid

Decisions and actions (Therefore we will...)
Therefore we will continue by doing a sanity check to see if the cells with the plasmid behave as expected. This consists of plating single colonies on both -ade and -ura plates.

**Comment by T-Wisse** [comment]
Currently I am not sure what I should put under False test and Metric here since any falsification comes from the same test

**Comment by leilaicruz** [comment]
> Criteria (We are right if)
> We are right if we observe a small number of colonies on the -Ade and an normal number of colonies on the -Ura plate. This should occur because in some but very few of the plasmids the Ade2 gene should be repaired, allowing for growth on -Ade if the plasmid is present. The plasmid also contains the ura gene, allowing for normal growth on -Ura if present.

So this success critera is for the sanity check after the transformation. So I would create another issue for that. 

Here is the success criteria for the transformation: so growth on SC-URA as the selection media for the plasmid , you should write here the genotype of the plasmid . do you have the snapgene file right?

**Comment by leilaicruz** [comment]
> Observation (We observed...)
> We observed colonies on the selection plates which smell like yeast.

So here refer to the actual observation ,  give a link to your experimental journal where you describe this in detail. 

And here you can write about the roughly number of colonies you have in the plates and their sizes for example.

**Comment by T-Wisse** [comment]
Okay we can indeed make another issue for the sanity check after transformation. So then the only verification that tranformation was succesful is that we have is that colonies grew on selection plates that seem to be yeast. The way I see it is that the sanity check is just an additional verification step of the transformation so that is why I added it here. Let's do it your way. 

Should I edit my original comment to make changes? Or add a new ajusted comment and keep the old one as well
