### ISSUE TITLE
SATAY on transformed yTW001 and yLIC137

### ISSUE THREAD

**Issue by T-Wisse** [T-Wisse/MEP_Thomas#19]
Preparation: To do SATAY we require several different liquid media as well agar plates. These will have to be prepared beforehand to save time. I will look up what we need and note it down below.

Hypothesis (We believe that...)
We believe that we can induce the transposon in the plasmid for many cells of our strains yTW001 and yLIC137 and allow them to grow for a number of generations (=perform SATAY) as [detailed by benoit](https://sites.google.com/site/satayusers/complete-protocol/liquid-library-generation-w303). 

Test (To verify that we will...)
Perform the protocol using our clones observed on the -Ura plates from the sanity check.

False Test (To falsify that we should test...)
Metric (And measure...)
We measure OD and measure the cells/ml as well as ADE+ cells/ml and URA+ cells/ml by plating throughout the preculture, induction and reseed steps. 

Criteria (We are right if...)
We are right if we observe a increase in ADE+ cells during induction and reseed similar to described by benoit. (% end of induction?). At the end of the reseed ~70% of cells should be ADE+ and expect a pellet of about 15ml. 

Observation (We observed...)
We observed an increase of ADE+ cells during induction, with 0.075 to 0.27% of ADE+ cells at the end of induction. At the end of the reseed the % of ADE+ cells ranged from 25% to 100% or 35% to 75%, depending on which plates are used to determine cells/ml. The pellet obtained was slightly lower than 15 ml.

Learnings and insights (From that we learned that...)
We have performed SATAY with some succes

Decisions and actions (Therefore we will...)
Continue by extracting the DNA of the pellet and preparing it for sequencing.

**Comment by T-Wisse** [comment]
[In progress] 

Based on [SATAY paper Michel et al. 2017](https://elifesciences.org/articles/23570) and previous [SATAY experiments of Leila](https://github.com/leilaicruz/Experimental-journal-jupyterBOOK/blob/master/mini_book/journal/2020-08/2020-08-10-SATAY-bem2d-nrp1d-WT.md)

- Preculture: SC -Ura +2% Raffinose +0.2% Dextrose (paper: One liter of freshly prepared media) Leila: add Ade for faster growth
- Induction: SC-URA+2% gal+ade
- Measure background induction
  - Plates: SC +2% Galactose - Adenine
  - Plates: SC-URA + Ade
  - Plates: CSM + Ade
- Plating in SC-ADE and SC-URA+Ade and CSM+Ade to check induction

**Comment by leilaicruz** [comment]
> Induction: SD-URA+2% gal (+ade?)

Yes with adenine 

> Measure background induction (essentially sanity check but more numeric)

it is not the same since you wont analyze colonies but the whole culture background  before induction

> Plating in SD-ADE and SD-URA to check induction

and also  in SC complete media 

- You need also reseed media SC-ADE , like 3L per strain
